# Generated by Django 5.1.4 on 2024-12-22 06:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_advertisement_homepage_news_bulletin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta', wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtailutils.blocks.PageChooserBlock', (), {'max_num': 1}), 1: ('wagtail.blocks.URLBlock', (), {'max_num': 1}), 2: ('wagtail.blocks.StreamBlock', [[('page', 0), ('link', 1)]], {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Read More', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('link', 2), ('anchor', 3), ('label', 4)]], {})}, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='news_bulletin',
        ),
    ]
