# Generated by Django 5.1.4 on 2024-12-17 09:22

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_news_bulletin'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmarBarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(help_text='Main Heading of the News', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle of the News', max_length=255, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publish Date and Time')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date and Time')),
                ('details', wagtail.fields.RichTextField(blank=True, help_text='Details of the news')),
                ('image', models.ForeignKey(blank=True, help_text='News Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amar_barta_images', to='wagtailimages.image')),
            ],
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
