# Generated by Django 5.1.4 on 2024-12-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_currentnews_remove_homepage_news_bulletin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentnews',
            name='cta',
        ),
    ]
