# Generated by Django 5.1.4 on 2024-12-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_currentnews_newscategory_newsindexpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetailspage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='newsdetailspage',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='repeated_item_text',
        ),
    ]
