# Generated by Django 5.1.4 on 2024-12-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_amarbarta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amarbarta',
            options={'verbose_name': 'Amar Barta', 'verbose_name_plural': 'Amar Bartas'},
        ),
    ]
