# Generated by Django 5.1.4 on 2024-12-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_currentnews_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentnews',
            name='news_bulletin',
            field=models.CharField(default=2, help_text='Enter news items separated by a pipe (|) or dot (•).', max_length=500),
            preserve_default=False,
        ),
    ]
