# Generated by Django 5.1.4 on 2024-12-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_newsdetailspage_repeat_in_subnav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetailspage',
            name='main_heading',
            field=models.CharField(blank=True, help_text='Main Heading of the News', max_length=255),
        ),
    ]
