# Generated by Django 5.1.4 on 2024-12-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_amarbarta_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amarbarta',
            name='image',
            field=models.ForeignKey(default=1, help_text='News Image', on_delete=django.db.models.deletion.CASCADE, related_name='amar_barta_images', to='wagtailimages.image'),
            preserve_default=False,
        ),
    ]
