# Generated by Django 5.1.4 on 2024-12-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_currentnews_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='News Category')),
            ],
        ),
        migrations.AlterField(
            model_name='currentnews',
            name='news_bulletin',
            field=models.CharField(help_text='Enter news heading', max_length=500),
        ),
        migrations.AlterField(
            model_name='currentnews',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
