# Generated by Django 5.1.4 on 2024-12-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_amarbarta_id'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='amarbarta',
            name='image2',
            field=models.ForeignKey(blank=True, help_text='Optimal_Dimension : 485x320', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
