# Generated by Django 5.1.4 on 2024-12-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_amarbarta_image2'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amarbarta',
            name='image2',
        ),
        migrations.AlterField(
            model_name='amarbarta',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optimal_Dimension : 485x320', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
