# Generated by Django 5.1.4 on 2024-12-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_missingmessage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingmessage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='missingmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=234, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
