# Generated by Django 5.1.4 on 2024-12-19 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_amarbarta_image2_alter_amarbarta_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the missing person', null=True, upload_to='missing_messages/')),
                ('name', models.CharField(help_text='Name of the missing person', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Age of the missing person')),
                ('skin_tone', models.CharField(help_text='Skin tone of the missing person', max_length=100)),
                ('dress', models.CharField(help_text='Description of the dress the missing person was wearing', max_length=255)),
                ('missing_time_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Time and date when the person went missing')),
                ('contact_number', models.CharField(help_text='Contact number to reach out for information', max_length=15)),
                ('detail_story', models.TextField(help_text='Detailed story of the missing incident')),
            ],
            options={
                'verbose_name': 'Missing Message',
                'verbose_name_plural': 'Missing Messages',
            },
        ),
        migrations.AlterField(
            model_name='amarbarta',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optimal_Dimension : 520x365', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
