# Generated by Django 5.1.4 on 2024-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_missingmessage_alter_amarbarta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingmessage',
            name='published_date',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date and Time'),
        ),
    ]
