# Generated by Django 5.1.4 on 2024-12-25 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_missingnewspage_alter_newscategory_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailmenus', '0023_remove_use_specific'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu Title 1')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text')),
                ('facebook', models.URLField(blank=True, max_length=255, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=255, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, max_length=255, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, max_length=255, verbose_name='Youtube')),
                ('menu_column_title_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu Column Title 1')),
                ('menu_column_title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu Column Title 2')),
                ('copyright_line', models.CharField(blank=True, default='Copyright © 2022 SAJIDA. All right reserved.', max_length=255, verbose_name='copyright')),
                ('menu_column_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmenus.flatmenu', verbose_name='Menu Column 1')),
                ('menu_column_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmenus.flatmenu', verbose_name='Menu Column 2')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
        migrations.DeleteModel(
            name='AmarBarta',
        ),
    ]
