# Generated by Django 5.1.4 on 2024-12-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footersettings_delete_amarbarta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_line',
            field=models.CharField(blank=True, default='Copyright © 2024 Child Message. All right reserved.', max_length=255, verbose_name='copyright'),
        ),
    ]
