# Generated by Django 5.1.4 on 2024-12-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_missingmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the missing person', null=True, upload_to='missing_messages/'),
        ),
    ]
