# Generated by Django 5.1.4 on 2024-12-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_footersettings_copyright_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildGeneralist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Mother's Name")),
                ('student_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Child Generalist Form',
                'verbose_name_plural': 'Child Generalist Forms',
            },
        ),
        migrations.CreateModel(
            name='ChildPresenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Mother's Name")),
                ('student_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Child Presenter Form',
                'verbose_name_plural': 'Child Presenter Forms',
            },
        ),
    ]
