# Generated by Django 5.1.4 on 2024-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childgeneralist',
            name='district',
            field=models.CharField(choices=[('কুমিল্লা', 'কুমিল্লা'), ('ফেনী', 'ফেনী'), ('ব্রাহ্মণবাড়িয়া', 'ব্রাহ্মণবাড়িয়া'), ('রাঙ্গামাটি', 'রাঙ্গামাটি'), ('নোয়াখালী', 'নোয়াখালী'), ('চাঁদপুর', 'চাঁদপুর'), ('লক্ষ্মীপুর', 'লক্ষ্মীপুর'), ('চট্টগ্রাম', 'চট্টগ্রাম'), ('কক্সবাজার', 'কক্সবাজার'), ('খাগড়াছড়ি', 'খাগড়াছড়ি'), ('বান্দরবান', 'বান্দরবান')], default=234, max_length=50, verbose_name='District Name'),
            preserve_default=False,
        ),
    ]
