# Generated by Django 5.1.4 on 2024-12-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_mainmenu_menuitem'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Optimal_Dimension : max width 190px', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Footer logo'),
        ),
    ]
