# Generated by Django 5.1.4 on 2024-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_footersettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('link', models.URLField(blank=True, help_text='External link.', null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, help_text='External link.', null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
