# Generated by Django 5.1.4 on 2024-12-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_hotline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheifvoicepage',
            options={'verbose_name': 'Chief Voice Page'},
        ),
    ]
