# Generated by Django 5.1.4 on 2024-12-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_cheifvoicepage_options'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheifvoicepage',
            options={},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Link to a Wagtail page (required).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
