# Generated by Django 5.1.4 on 2024-12-30 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_cheifvoicepage_options_remove_menuitem_link_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=255, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=255, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, max_length=255, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, max_length=255, verbose_name='Youtube')),
                ('hotline_name', models.CharField(help_text='Hotline number', max_length=25)),
                ('child_helpline_number', models.CharField(help_text='Child helpline number', max_length=20)),
                ('copyright_line', models.CharField(blank=True, default='Copyright © 2024 Child Message. All rights reserved.', max_length=255, verbose_name='copyright')),
                ('short_message', models.CharField(help_text='Short message', max_length=255)),
                ('quick_link_1_name', models.CharField(help_text='Quick link 1 name', max_length=255)),
                ('quick_link_1_url', models.URLField(blank=True, max_length=255, verbose_name='Quick link 1 URL')),
                ('quick_link_2_name', models.CharField(help_text='Quick link 2 name', max_length=255)),
                ('quick_link_2_url', models.URLField(blank=True, max_length=255, verbose_name='Quick link 2 URL')),
                ('quick_link_3_name', models.CharField(help_text='Quick link 3 name', max_length=255)),
                ('quick_link_3_url', models.URLField(blank=True, max_length=255, verbose_name='Quick link 3 URL')),
                ('quick_link_4_name', models.CharField(help_text='Quick link 4 name', max_length=255)),
                ('quick_link_4_url', models.URLField(blank=True, max_length=255, verbose_name='Quick link 4 URL')),
                ('quick_link_5_name', models.CharField(help_text='Quick link 5 name', max_length=255)),
                ('quick_link_5_url', models.URLField(blank=True, max_length=255, verbose_name='Quick link 5 URL')),
                ('quick_link_6_name', models.CharField(help_text='Quick link 6 name', max_length=255)),
                ('quick_link_6_url', models.URLField(blank=True, max_length=255, verbose_name='Quick link 6 URL')),
                ('logo', models.ForeignKey(blank=True, help_text='Optimal Dimension: max width 190px', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Site logo')),
            ],
            options={
                'verbose_name': 'Site associate',
            },
        ),
    ]
