# Generated by Django 5.1.4 on 2024-12-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_site_associate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterSettings',
        ),
    ]
