# Generated by Django 5.1.4 on 2024-12-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_footersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_associate',
            old_name='hotline_name',
            new_name='hotline_number',
        ),
    ]
