# Generated by Django 5.1.4 on 2024-12-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_site_associate_child_helpline_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotline',
        ),
    ]
