# Generated by Django 5.1.4 on 2025-01-01 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_childgeneralist_district_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(blank=True, help_text='Main Heading of the News', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle of the News', max_length=255, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publish Date and Time')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date and Time')),
                ('details', models.TextField(blank=True, help_text='Details of the news')),
                ('make_featured_news', models.BooleanField(blank=True, default=False, verbose_name='Make it featured?')),
                ('image', models.ForeignKey(blank=True, help_text='Optimal_Dimension : 520x365', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('news_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_details', to='home.newscategory', verbose_name='Select a Category')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsDetailsPage',
        ),
    ]
