# Generated by Django 5.1.4 on 2025-01-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_newsdetails_options_newsdetails_page_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetails',
            name='news_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_category', to='home.newscategory', verbose_name='News Category'),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='page_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_page', to='home.newsindexpage', verbose_name='Associated page'),
        ),
    ]
