# Generated by Django 5.1.4 on 2025-01-01 21:36

import home.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_newsdetails_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_categories',
            field=wagtail.fields.StreamField([('News_Category', 1)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': home.models.get_news_category_choices, 'label': 'News Category'}), 1: ('wagtail.blocks.StructBlock', [[('category', 0)]], {})}, null=True),
        ),
    ]
