# Generated by Django 5.1.4 on 2025-01-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_homepage_news_categories'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_associate',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Link to a Wagtail page (required).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
