# Generated by Django 5.1.4 on 2025-01-02 09:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_page_site_associate_quick_link_4_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news_categories',
            field=wagtail.fields.StreamField([('Main_Featured_News', 5)], blank=True, block_lookup={0: ('wagtailutils.blocks.PageChooserBlock', (), {'max_num': 1}), 1: ('wagtail.blocks.URLBlock', (), {'max_num': 1}), 2: ('wagtail.blocks.StreamBlock', [[('page', 0), ('link', 1)]], {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('link', 2), ('anchor', 3)]], {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('cta', 4)]], {})}, null=True),
        ),
    ]
