# Generated by Django 5.1.4 on 2025-01-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_homepage_news_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetails',
            name='make_featured_news',
        ),
    ]
